### ISSUE TITLE
Peer to Peer code review Module 2 Week 2

### ISSUE THREAD

**Issue by mirouhml** [AyoubMs/To-Do-list#4]
## Hi @AyoubMs    , :wave: 

**We want to express our appreciation for your work. It looks nice, and for the most part responsive** :rocket:

**However, we have a suggestion for you:**

- [x] **Try to use DOM events** - It's better to use DOM events when adding event listeners than using the "window" attribute in JavaScript.

Please feel free to ask for any more clarification about what we mentioned.
Happy Coding! :rocket: 

![](https://media0.giphy.com/media/l3BwSPbqx3QGKEgpp2/200w.webp?cid=ecf05e476e3lbd0evinaj2rb4o1w58sck4h0sqnmyioczedk&rid=200w.webp&ct=g)

**Comment by AyoubM490** [comment]
Thanks
